export const projectsList = [
  {
    id: 1,
    name: "16Bit Gamestore",
    description: "Retro games e-commerce from scratch.",
    image: "/images/16bitgamestore.png",
    link: "https://16-bit-gamestore.vercel.app/home",
    GitHub: "https://github.com/2Davit/16Bit-GameStore",
    project: "16bit-gamestore",
    tools: [
      "React",
      "Redux",
      "TypeScript",
      "Express.js",
      "JWT",
      "Sequelize",
      "PostgreSQL",
      "Node.js",
      "StyledComponents",
    ],
  },
  {
    id: 2,
    name: "Pokedex SPA",
    description: "A SPA that consumes API Data from PokeAPI",
    image: "/images/pokedex.png",
    link: "https://pokedexapp-gold.vercel.app/",
    GitHub: "https://github.com/chakkyy/pokedex-app",
    project: "pokedexfs",
    tools: ["React", "Firebase", "Redux", "Styled Components"],
  },
  {
    id: 3,
    name: "Born In Garage",
    description: "A simple car engine sound library",
    image: "/images/borningarage.png",
    link: "https://borningarage.vercel.app/",
    project: "borningarage",
    GitHub: "https://github.com/chakkyy/borningarage",
    tools: ["React", "Sass"],
  },
  {
    id: 4,
    name: "Earth App",
    description:
      "A SPA That consumes data of countries from RESTcountries API ",
    image: "/images/countriesapp.png",
    project: "countriesapp",
    GitHub: "https://github.com/chakkyy/countries-app",
    tools: [
      "React",
      "Redux",
      "Axios",
      "Sass",
      "PostgreSQL",
      "Express.js",
      "Sequelize",
      "Node.js",
    ],
  },
  {
    id: 5,
    name: "Weather App",
    description:
      "My very first project was an weather app that consumes OpenWeather API data",
    image: "/images/weather.png",
    link: "https://weather-app-seven-red.vercel.app/",
    project: "weatherapp",
    GitHub: "https://github.com/chakkyy/weather-app",
    tools: ["React", "Styled Components"],
  },
];
